//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTMLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConstModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTMLib.Resources.ConstModels", typeof(ConstModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 广播词.
        /// </summary>
        public static string CabinAnnoucement {
            get {
                return ResourceManager.GetString("CabinAnnoucement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乘务员.
        /// </summary>
        public static string CabinCrew {
            get {
                return ResourceManager.GetString("CabinCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乘务员ID.
        /// </summary>
        public static string CabinCrewID {
            get {
                return ResourceManager.GetString("CabinCrewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        public static string CabinCrewName {
            get {
                return ResourceManager.GetString("CabinCrewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分类ID.
        /// </summary>
        public static string CategoryID {
            get {
                return ResourceManager.GetString("CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 危险品培训管理员.
        /// </summary>
        public static string DangerousGoodsTrainingAdmin {
            get {
                return ResourceManager.GetString("DangerousGoodsTrainingAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英语培训管理员.
        /// </summary>
        public static string EnglishTestAdmin {
            get {
                return ResourceManager.GetString("EnglishTestAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 考核项目.
        /// </summary>
        public static string EnglishTestType {
            get {
                return ResourceManager.GetString("EnglishTestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失效日期.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始日期.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成绩.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅显示最新成绩 .
        /// </summary>
        public static string IsLatestResultOnly {
            get {
                return ResourceManager.GetString("IsLatestResultOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否已离职.
        /// </summary>
        public static string IsResigned {
            get {
                return ResourceManager.GetString("IsResigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否已撤销.
        /// </summary>
        public static string IsWithdrawn {
            get {
                return ResourceManager.GetString("IsWithdrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 普通用户.
        /// </summary>
        public static string OrdinaryUser {
            get {
                return ResourceManager.GetString("OrdinaryUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 晋级管理员.
        /// </summary>
        public static string PromotionAdmin {
            get {
                return ResourceManager.GetString("PromotionAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复训管理员.
        /// </summary>
        public static string RefresherTrainingAdmin {
            get {
                return ResourceManager.GetString("RefresherTrainingAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 口语.
        /// </summary>
        public static string SpokenSkill {
            get {
                return ResourceManager.GetString("SpokenSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 子类型.
        /// </summary>
        public static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超级管理员.
        /// </summary>
        public static string SuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分类.
        /// </summary>
        public static string SuperCategory {
            get {
                return ResourceManager.GetString("SuperCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束日期.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
    }
}
