//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTMLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConstModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTMLib.Resources.ConstModels", typeof(ConstModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabin Announcement.
        /// </summary>
        public static string CabinAnnoucement {
            get {
                return ResourceManager.GetString("CabinAnnoucement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabin Crew.
        /// </summary>
        public static string CabinCrew {
            get {
                return ResourceManager.GetString("CabinCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CabinCrew ID.
        /// </summary>
        public static string CabinCrewID {
            get {
                return ResourceManager.GetString("CabinCrewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CabinCrewName {
            get {
                return ResourceManager.GetString("CabinCrewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID.
        /// </summary>
        public static string CategoryID {
            get {
                return ResourceManager.GetString("CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Goods Training Administrator.
        /// </summary>
        public static string DangerousGoodsTrainingAdmin {
            get {
                return ResourceManager.GetString("DangerousGoodsTrainingAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Test.
        /// </summary>
        public static string EnglishTest {
            get {
                return ResourceManager.GetString("EnglishTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Test Administrator.
        /// </summary>
        public static string EnglishTestAdmin {
            get {
                return ResourceManager.GetString("EnglishTestAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Test Type.
        /// </summary>
        public static string EnglishTestType {
            get {
                return ResourceManager.GetString("EnglishTestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the latest results only.
        /// </summary>
        public static string IsLatestResultOnly {
            get {
                return ResourceManager.GetString("IsLatestResultOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is resigned.
        /// </summary>
        public static string IsResigned {
            get {
                return ResourceManager.GetString("IsResigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is withdrawn.
        /// </summary>
        public static string IsWithdrawn {
            get {
                return ResourceManager.GetString("IsWithdrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string OrdinaryUser {
            get {
                return ResourceManager.GetString("OrdinaryUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Administrator.
        /// </summary>
        public static string PromotionAdmin {
            get {
                return ResourceManager.GetString("PromotionAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresher Training.
        /// </summary>
        public static string RefresherTraining {
            get {
                return ResourceManager.GetString("RefresherTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresher Training Administrator.
        /// </summary>
        public static string RefresherTrainingAdmin {
            get {
                return ResourceManager.GetString("RefresherTrainingAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoken English.
        /// </summary>
        public static string SpokenSkill {
            get {
                return ResourceManager.GetString("SpokenSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category.
        /// </summary>
        public static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Administrator.
        /// </summary>
        public static string SuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Category.
        /// </summary>
        public static string SuperCategory {
            get {
                return ResourceManager.GetString("SuperCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
    }
}
